server:
  port: 8081

spring:
  application:
    name: host-service
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:postgresql://localhost:5432/voting
    username: db
    password: password

  redis:
    #    host: redis
    host: localhost
    port: 6379

  data:
    mongodb:
      #      Change to localhost:27017 for local and mongodb:27017 for docker
      uri: mongodb://root:password@localhost:27017/
      #      uri: mongodb://root:password@localhost:27017/
      username: root
      password: password
      database: surveyDB

## LOGGING
logging:
  level:
    root: INFO
    com.voting: DEBUG
  file:
    name: ./logs/survey-host.log
shared:
  log:
    dir: ~/logs