server:
  port: 8081

spring:
  application:
    name: host-service
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:postgresql://localhost:5432/voting
    username: db
    password: password

  redis:
    #    host: redis
#    host: localhost
    host: redis-service
    port: 6379

  data:
    mongodb:
      host: mongo-service
      port: 27017
      database: surveyDB

## LOGGING
logging:
  level:
    root: INFO
    com.voting: DEBUG
  file:
    name: ./logs/survey-host.log
shared:
  log:
    dir: ~/logs